### ISSUE TITLE
提示配置保存失败。

### ISSUE THREAD

**Issue by DearTanker** [Se7enMuting/koolshare-cfddns#1]
![qq 20181221201416](https://user-images.githubusercontent.com/1122669/50342183-070e8400-055d-11e9-8d0c-82f3bedbc9e6.png)
百思不得其解

**Comment by se7enmuting** [comment]
zone name：就是一级域名，不是zone ID.....
另外CF的API好像有写改，有空我要改下~~

**Comment by se7enmuting** [comment]
更新了一版，支持X7.9.1固件，API错误修复，使用注意见README.md
